---
- name: Configure Project Management System
  hosts: all
  become: yes
  roles:
    - common
    - docker
    - monitoring
    - applications

- name: Configure Monitoring Stack
  hosts: monitoring
  become: yes
  roles:
    - prometheus
    - grafana

- name: Configure Application Stack
  hosts: applications
  become: yes
  roles:
    - nodejs
    - postgresql
    - nginx 